#!/bin/bash
set -euo pipefail

REPO_DIR="/data/neurogroup/mingyangjiang/EEGxPlore/LaBraM"
cd "$REPO_DIR"

COMMIT="$(git rev-parse HEAD)"
SEEDV_CHANNEL_MANIFEST="${SEEDV_CHANNEL_MANIFEST:-$REPO_DIR/docs/seedv_channel_manifest_provisional.json}"
SEEDS="${SEEDS:-42 1024 3407}"

# Final matched frozen PEFT matrix. Every condition uses the D1 head recipe:
# deterministic frozen features, no warmup, no smoothing, and no head WD.
BATCH_SIZE="${BATCH_SIZE:-32}"
LR="${LR:-1e-4}"
EPOCHS="${EPOCHS:-40}"
WEIGHT_DECAY="${WEIGHT_DECAY:-0.03}"
LAYER_DECAY="${LAYER_DECAY:-0.65}"
DROP_PATH="${DROP_PATH:-0.1}"
INPUT_SCALE_DIVISOR="${INPUT_SCALE_DIVISOR:-100.0}"

for SEED in $SEEDS; do
  for ADAPTER in none channel patch; do
    RUN_ID="seedv_labram_frozen_d1_${ADAPTER}_s${SEED}_b${BATCH_SIZE}_headlr1e-3_e${EPOCHS}_test"
    sbatch \
      --export=ALL,EXPECTED_COMMIT="$COMMIT",REQUIRE_CLEAN_TREE=1,ALLOW_EXISTING_OUTPUT=0,\
SEED="$SEED",RUN_ID="$RUN_ID",SEEDV_CHANNEL_MANIFEST="$SEEDV_CHANNEL_MANIFEST",\
LABRAM_BACKBONE_MODE=frozen,LABRAM_ADAPTER_TYPE="$ADAPTER",LABRAM_ADAPTER_VARIANT=full,\
BACKBONE_LR_SCALE=0.0,FROZEN_BACKBONE_EVAL_MODE=1,HEAD_LR_SCALE=10.0,HEAD_WEIGHT_DECAY=0.0,\
LABRAM_ADAPTER_INIT_ALPHA=0.01,LABRAM_ADAPTER_GAMMA=1.0,LABRAM_ADAPTER_LR_SCALE=1.0,\
LABRAM_ADAPTER_ALPHA_LR_SCALE=1.0,LABRAM_ADAPTER_DEPTH_MODE=none,\
BATCH_SIZE="$BATCH_SIZE",LR="$LR",EPOCHS="$EPOCHS",WARMUP_EPOCHS=0,\
WEIGHT_DECAY="$WEIGHT_DECAY",LAYER_DECAY="$LAYER_DECAY",DROP_PATH="$DROP_PATH",\
SMOOTHING=0.0,INPUT_SCALE_DIVISOR="$INPUT_SCALE_DIVISOR",NUM_WORKERS=0,\
SKIP_FINAL_TEST=0 \
      scripts/submit_seedv_finetune_accre.slurm
  done
done
